Improve and Fix things MIUI
urbandroid-team/dont-kill-my-app pull request #372
Opened 2021-11-17 12:15 UTC by XomaDev

2021-11-18 11:26 UTC, Artaud approved these changes

2021-11-18 11:26 UTC, merged

2021-11-18 11:26 UTC, Artaud commented
Big thanks!

2025-01-20 18:56 UTC, troublemaker420 requested changes

2025-01-20 18:56 UTC, troublemaker420 commented on _vendors-content/xiaomi/dev.md
> -### MIUI 10 or lower
-